service: yoube-api-auth
provider:
  name: aws
  apiKeys:
    - api_ios
  runtime: nodejs8.10 
functions:
  users-show-get:
    handler: AuthControllers.show
    events:
      - http:
          path: /auth/show
          method: get
          cors: true
          private: true
  users-signin:
    handler: AuthControllers.signIn
    events:
      - http:
          path: /auth/sign_in
          method: post
          cors: true
          private: true
  users-signup:
    handler: AuthControllers.signUp
    events:
      - http:
          path: /auth/sign_up
          method: post
          cors: true
          private: true
  users-signout:
    handler: AuthControllers.signOut
    events:
      - http:
          path: /auth/sign_out
          method: post
          cors: true
          private: true
  users-confirmation-code:
    handler: AuthControllers.confirmCode
    events:
      - http:
          path: /auth/confirmation_code
          method: post
          cors: true
          private: true
  users-forgotpassword:
    handler: AuthControllers.forgotPassword
    events:
      - http:
          path: /auth/forgot_password
          method: post
          cors: true
          private: true
  users-confirm-forgotpassword:
    handler: AuthControllers.confirmForgotPassword
    events:
      - http:
          path: /auth/confirm_forgot_password
          method: post
          cors: true
          private: true
  users-changepassword:
    handler: AuthControllers.changePassword
    events:
      - http:
          path: /auth/change_password
          method: put
          cors: true
          private: true
  users-update:
    handler: AuthControllers.update
    events:
      - http:
          path: /auth/update
          method: put
          cors: true
          private: true
          
plugins:
  - serverless-iam-roles-per-function
  - serverless-domain-manager
  - serverless-offline


custom:
  customDomain:
    certificateName: '*ioasys.com.br'
    domainName: 'apiyoube.ioasys.com.br' # Change this to your domain.
    basePath: 'dev' # This will be prefixed to all routes
    # stage: ${self:provider.stage}
    createRoute53Record: true
