service: sls-boilerplate-sequilize

provider:
  name: aws
  runtime: nodejs8.10

functions:
  users:
    handler: UsersControllers.usersAll
    events:
    - http:
        path: users
        method: get
  create:
    handler: UsersControllers.create
    events:
    - http:
        path: users
        method: post


plugins:
  - serverless-offline