service: yoube-api-users


provider:
  name: aws
  runtime: nodejs8.10 


functions:
  users-show-get:
    handler: show.show
    events:
      - http:
          path: /
          method: get
          cors: true
  users-signin:
    handler: sign_in.signin
    events:
      - http:
          path: /auth
          method: post
          cors: true
  users-signout:
    handler: sign_out.signout
    events:
      - http:
          path: /auth/sign_out
          method: post
          cors: true
  users-confirm-code:
    handler: confirm_code.confirm
    events:
      - http:
          path: /confirm_code
          method: post
          cors: true
  users-forgot-password:
    handler: forgot_password.forgotpassword
    events:
      - http:
          path: /forgot_password
          method: post
          cors: true
  users-confirm-forgot-password:
    handler: confirm_forgot_password.confirmforgotpassword
    events:
      - http:
          path: /confirm_forgot_password
          method: post
          cors: true
  users-change_password:
    handler: change_password.changepassword
    events:
      - http:
          path: /change_password
          method: put
          cors: true
          
plugins:
  - serverless-iam-roles-per-function
  - serverless-domain-manager


custom:
  customDomain:
    certificateName: '*ioasys.com.br'
    domainName: 'api-yoube.ioasys.com.br' # Change this to your domain.
    basePath: 'users' # This will be prefixed to all routes
    # stage: ${self:provider.stage}
    createRoute53Record: true
